---
title: "Report"
author: "Hauer-Glocke"
date: "8 Juli 2017"
output: pdf_document
---

#Sample Project Report Structure

Of course, there are multiple ways one could structure a report to address the requirements above. However, the more clearly you pose and answer each question, the easier it will be for reviewers to clearly identify and evaluate your work.

A sample set of headings that could be used to guide the creation of your report might be:

* **Title** (give an appropriate title) and *Author Name*
* **Overview:** In a few (2-3) sentences explain what is going to be reported on.
* **Simulations:**Include English explanations of the simulations you ran, with the accompanying R code. Your explanations should make clear what the R code accomplishes.
* **Sample Mean versus Theoretical Mean:** Include figures with titles. In the figures, highlight the means you are comparing. Include text that explains the figures and what is shown on them, and provides appropriate numbers.
* **Sample Variance versus Theoretical Variance:** Include figures (output from R) with titles. Highlight the variances you are comparing. Include text that explains your understanding of the differences of the variances.
* **Distribution:** Via figures and text, explain how one can tell the distribution is approximately normal.

#Review criteria

* Did you show where the distribution is centered at and compare it to the theoretical center of the distribution?
* Did you show how variable it is and compare it to the theoretical variance of the distribution?
* Did you perform an exploratory data analysis of at least a single plot or table highlighting basic features of the data?
* Did the student perform some relevant confidence intervals and/or tests?
* Were the results of the tests and/or intervals interpreted in the context of the problem correctly?
* Did the student describe the assumptions needed for their conclusions?
